### ISSUE TITLE
The login boxes do not scale for fullscreen, making it look slightly odd

### ISSUE THREAD

**Issue by MrAttoAttoAtto** [bhuvan21/arx-noctis#10] opened 2019-07-27 13:38 UTC
See layout: https://imgur.com/a/I5pPajq

**Comment by bhuvan21** [comment] 2019-07-27 20:10
The link is appreciated
I believe the issue is now fixed, but I won't mark this as closed until the next build is live, to be sure

**Comment by MrAttoAttoAtto** [comment] 2019-07-27 20:10
I think that’s good practice for all issues btw

**Comment by bhuvan21** [comment] 2019-07-27 20:13
noted, and will be done for issues down the line, but stuff like scaling can be especially dodgy in testing

**Comment by bhuvan21** [comment] 2019-07-28 06:25
looks to be fixed, reopen if you still experience oddness

**Closed as completed by bhuvan21** 2019-07-28 06:25 UTC
Labels: done?
